FROM ubuntu:20.04 as target
SHELL ["/bin/bash", "-o", "pipefail", "-c"]

ARG PRT_PACKAGE=prt_latest.tgz
ARG PRT_ROOT=/prt

RUN apt update && apt install -y openssl jq
COPY test-runtime /test-runtime
ADD ${PRT_PACKAGE} ${PRT_ROOT}/
