#!/usr/bin/env bash
set -euETo pipefail
shopt -s inherit_errexit

# Install pylint plugin without deps so that it does not upgrade pydantic package
${PRT_ROOT}/bin/pip install --no-deps pylint-pydantic

# Install source version of pydantic for better debugging
${PRT_ROOT}/bin/pip uninstall --yes pydantic
${PRT_ROOT}/bin/pip install --no-deps --no-binary=pydantic pydantic==1.10.12
