#!/usr/bin/env bash
set -euETo pipefail
shopt -s inherit_errexit

# Install ansible and development tools in a virtual env
venv_path="${PRT_VENV_ROOT}/ansible"
${PRT_ROOT}/bin/python -m venv "${venv_path}"

source "${venv_path}"/bin/activate

pip install --no-user wheel
pip install --no-user \
        ansible==5.7.0 \
        ansible-core==2.12.5 \
        ansible-lint \
        docker \
        jmespath
# Create a script to run ansible from the venv
script_path="${PRT_ROOT}/bin/ansible"
cat << EOF | tee "${script_path}"
#!/usr/bin/env bash
set -euETo pipefail
shopt -s inherit_errexit
source "${venv_path}"/bin/activate
trap "deactivate" EXIT
script=\$(basename "\$0")
exec \${script} "\$@"
EOF
chmod +x "${script_path}"
# Create links for each tool
for tool in $(find "${venv_path}"/bin/ -name "ansible-*" -executable -exec basename {} \;); do
    ( cd ${PRT_ROOT}/bin; ln -s $(basename "${script_path}") ${tool} )
done
