#!/usr/bin/env bash
set -euETo pipefail
shopt -s inherit_errexit

# Install ansible and development tools in a virtual env
${PRT}/bin/python -m venv /ansible
source /ansible/bin/activate

pip install --no-user wheel
pip install --no-user \
        ansible==5.7.0 \
        ansible-core==2.12.5 \
        ansible-lint \
        docker \
        jmespath
